### ISSUE TITLE
a likely faster `fromList`

### ISSUE THREAD

**Issue by lue-bird** [miniBill/elm-fast-dict#2]
Changing it to just
```elm
fromList : List ( comparable, v ) -> Dict comparable v
fromList list =
    Internal.fromSortedList
        (ListWithLength.ListWithLength (List.length list)
            (List.sortBy Tuple.first list)
        )
```
- firefox without --optimize ![image](https://github.com/miniBill/elm-fast-dict/assets/81869893/45e9c967-b29e-4c2c-a62c-9e610498e7a0)
- chromium without --optimize ![image](https://github.com/miniBill/elm-fast-dict/assets/81869893/56e2da91-5d32-42b6-8203-88fde58472fa)
- firefox with --optimize ![image](https://github.com/miniBill/elm-fast-dict/assets/81869893/73c656ce-ed80-49af-a7bf-d4e83272ee4f)
- chromium with --optimize ![image](https://github.com/miniBill/elm-fast-dict/assets/81869893/4d1fc25f-7f2b-452c-bf7e-3da92fd00548)
- firefox with elm-optimize-level-2 -optimize-speed ![image](https://github.com/miniBill/elm-fast-dict/assets/81869893/da3c354e-2b93-4e5e-88f1-73847a424b23)
- chromium with elm-optimize-level-2 -optimize-speed ![image](https://github.com/miniBill/elm-fast-dict/assets/81869893/753fc44a-2808-4650-a541-34327066a84b)

The comparison was done on a list with 500 randomized ints as keys.

Do you think this change is worth making at the cost of slightly worse eol2 chromium performance?

**Comment by miniBill** [comment]
Wouldn't this give wrong results if the input list contains duplicates?

**Comment by lue-bird** [comment]
You're right
